### PR TITLE
grove: Modify modules to use the `degu` module

### PR DESCRIPTION
**Pull request by r4clet**
Degu v1.0.0 or above will provide the `degu` module instead of the `zcoap` module.
This pull request modifies the modules to correspond to the change.

### CODE REVIEW

**Comment by ohsawa** [comment]
I'd like to check with you exactly, but is this source code not compatible with Degu v0.9.x?

**Comment by takumiando** [comment]
No, it isn't.
We cannot apply this patch set to master branch before releasing Degu v1.0.0.

But this PR looks so nice :)

**Comment by takumiando** [comment]
I'd like you to apply the same changes to `/basic` samples.
Of course you can separate to another PR.

**Comment by takumiando** [comment]
Sorry, I had forgotten!

In the current release, `default` code shows the status of network(did Degu join to Thread network or not).

But we don't need to use the `default` code in Degu v1.0.0.
Because the same function will be implemented in C layer.
https://github.com/takumiando/degu/blob/degu-v1.0.0-work6/degu_utils.c#L248

So we should delete(or change the function of) the `default` code.

**Comment by takumiando** [comment]
Of course your changes to `/basic` samples are okay ;)

**Pull request merged**
